AirboZH/halo-theme-chirpy

templates/modules/widgets/trending-tags.html
templates/post.html

fix: 修复一些链接地址错误的问题

---

templates/index.html

fix: 修复自动生成摘要不显示的问题

---

.github/workflows/build.yml
.github/workflows/release.yml

chore: add GitHub Actions workflows

---

.prettierrc
templates/post.html

feat: 文章页阅读时间和文章字数统计 (#20)

---

.github/workflows/build.yml
.prettierrc
templates/post.html

chore: release v1.0.4

---

theme.yaml

fix: fix require halo version

---

src/js/modules/halo.js
src/js/modules/layouts/sidebar.js
templates/modules/mode-toggle.html
templates/page.html
templates/post.html

feat: support comment plugin

---

settings.yaml
templates/modules/footer.html
templates/post.html

Resolve #23 
Link #31
Add: 底部自定义备案号

feat: 版权许可

---

src/js/modules/halo.js

fix: 主题颜色切换时的JS错误

---

src/js/modules/layouts/basic.js
src/js/patch/index.js

feat: 支持行内代码块样式

---

templates/modules/post/relatedPosts.html
templates/post.html

Resolve #24
Resolve #26
Resolve #27

feat: 阅读建议

---

templates/archives.html
templates/page.html

Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/85#issue-1898775640
Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/83#issue-1898057199

Fix: 归档页面文字未对齐以及自定义页面网页标签问题

---

templates/error/error.html

Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/88#issue-1903235884

feat: 添加异常页面

---

templates/error/error.html

Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/97#issue-1910263396

fix: 错误页面标题重复显示

---

templates/page.html
templates/post.html

fix: 修复评论组件颜色和系统主题可能不一致的问题

---

src/css/patch/index.scss
src/css/patch/links.scss
templates/links.html

Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/123#issue-1988933137

feat: 添加友链模板

---

templates/post.html

chore: 移除文章页封面图

---

src/js/patch/sidebar.js
src/main.js

Resolve https://github.com/AirboZH/halo-theme-chirpy/issues/132#issue-2034279555

🎈 perf: 导航栏动态添加 active

---

package.json
pnpm-lock.yaml
src/css/colors/syntax-dark.scss
src/css/colors/syntax-light.scss
src/css/style.scss
src/js/modules/components/clipboard.js
src/js/patch/codeClass.js
src/js/patch/index.js
src/main.js
vite.config.js

feat: codeBlock

---

i18n/default.properties
i18n/en.properties
src/js/modules/components/clipboard.js
templates/category.html
templates/modules/head.html
templates/modules/post/postShaing.html
templates/modules/topbar.html
vite.config.js

优化复制文章链接的提示

---

src/css/patch/commons.scss

feat: image rounded

---

package.json
templates/page.html
templates/post.html
theme.yaml

fix: fix comment widget attr

---

package.json
src/css/addon/commons.scss
src/css/style.scss
src/js/modules/components/img-popup.js
src/js/patch/index.js
src/js/patch/pre-img.js
src/main.js
theme.yaml

pref: 优化图片效果

---

mode.js

fix: fix import.js tag bug

---

src/js/modules/components/img-popup.js

fix: magnificPopup js error

---

templates/post.html

fix: 修改 post-tail-wrapper 位置

---

theme.yaml

fix: release v1.4.6

---

package.json
templates/modules/mode-toggle.html
theme.yaml

允许使用 `html[data-mode="dark"]` 来选择暗色模式

增加对文本绘图的支持
